GET http://localhost:5177/games

### 
GET http://localhost:5177/games/3

###
POST http://localhost:5177/games
Content-Type: application/json

{
    "name": "Final Fantasy XIV",
    "genreId": 2,
    "price": 59.99,
    "releaseDate": "2012-02-01"
}

###
PUT http://localhost:5177/games/3
Content-Type: application/json

{
    "name": "Street Fighter 2 Turbo",
    "genreId": 1,
    "price": 19.99,
    "releaseDate": "1990-07-15"
}

###
DELETE http://localhost:5177/games/2


